name: Vitest@latest Compatibility

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # Every night at 00:00
    - cron: "0 0 * * *"

# Add permissions block at workflow level
permissions:
  contents: read
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"

      - name: Get current Vitest version
        id: current-version
        run: |
          # Usar jq para obtener la versión exacta
          CURRENT_VERSION=$(npm list vitest --json | jq -r '.dependencies.vitest.version')
          echo "current_version=${CURRENT_VERSION}" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: npm install

      - name: Install vitest@latest
        id: update-vitest
        run: |
          npm install --save-dev vitest@latest
          # Usar jq para obtener la versión exacta
          NEW_VERSION=$(npm list vitest --json | jq -r '.dependencies.vitest.version')
          echo "new_version=${NEW_VERSION}" >> $GITHUB_OUTPUT

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint
        continue-on-error: true

      - name: Test
        id: run-tests
        run: npm test
        continue-on-error: true

  playground:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Updated Node.js versions to match requirements
        node-version: [22]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies & Build
        run: |
          npm install
          npm run build

      - name: Run playground tests
        working-directory: ./playground
        run: |
          npm install
          npm test
        continue-on-error: true

  notify:
    needs: [build, playground]
    if: failure()
    runs-on: ubuntu-latest
    # Add permissions at job level as well for clarity
    permissions:
      issues: write
    steps:
      - name: Create Issue on Failure
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const runUrl = `${context.serverUrl}/${owner}/${repo}/actions/runs/${context.runId}`;

            await github.rest.issues.create({
              owner,
              repo,
              title: `⚠️ Compatibility Issue with Latest Vitest`,
              body: `The compatibility check with the latest version of Vitest has failed.

              This could be in either the main tests or playground tests.

              Please review the workflow run for more details: ${runUrl}

              This issue was automatically created by the Vitest compatibility check workflow.`
            });
